name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      # - name: Install SSH key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_KEY }}
      #     name: id_rsa # optional
      #     known_hosts: ${{ secrets.KNOWN_HOSTS }}
      #     if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - run: |
          npm install -g sfdy
          npm install
      - name: Deploy to Production
        env:
          target_branch: ${{ github.base_ref }}
          sf_username: ${{ secrets.sf_username_prod }}
          sf_password: ${{ secrets.sf_password_prod }}
          sf_serverurl: https://login.salesforce.com
        shell: bash
        run: sfdy deploy --server-url=${sf_serverurl} -u ${sf_username} -p ${sf_password} --diff=origin/${target_branch}..HEAD -t

  automerge:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: "micheletriaca/automerge-action@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""